#' Basic theme for ggplots
#'
#' @param base_size Size that various elements use.
#' @param base_family Font family to use.
#' @param base_line_size Defaults to base_size / 22.
#' @param base_rect_size Defaults to base_size / 22.
#'
#' @export
#'
#'

lb_theme <- function(base_size=11, base_family = "", base_line_size=base_size/22, base_rect_size=base_size/22, dark_mode=FALSE) {
  ggplot2::theme(line = ggplot2::element_line(color = ifelse(dark_mode, "white", "black"), size = base_line_size, linetype = 1, lineend = "butt"),
        rect = ggplot2::element_rect(fill = ifelse(dark_mode, "black", "white"), color = ifelse(dark_mode, "white", "black"), size = base_rect_size, linetype = 1),
        text = ggplot2::element_text(color = ifelse(dark_mode, "white", "black"), family = base_family, face = "plain", size = base_size, lineheight = 0.9,
                hjust = 0.5, vjust = 0.5, angle = 0, margin = ggplot2::margin()),
        axis.line = ggplot2::element_blank(),
        axis.line.x = NULL,
        axis.line.y = NULL,
        axis.text = ggplot2::element_text(margin = ggplot2::margin(t = 0.8 * base_size / 4), vjust = 1, color=ifelse(dark_mode, "white", "black")),
        axis.text.x.top = ggplot2::element_text(margin = ggplot2::margin(b = 0.8 * base_size / 4), vjust = 0),
        axis.text.y = ggplot2::element_text(margin = ggplot2::margin(r = 0.8 * base_size / 4), hjust = 1, vjust=0.5),
        axis.text.y.right = ggplot2::element_text(margin = ggplot2::margin(l = 0.8 * base_size / 4), hjust = 0),
        axis.ticks = ggplot2::element_line(colour = ifelse(dark_mode, "white", "black")),
        axis.ticks.length = ggplot2::unit(base_size / 4, "pt"),
        axis.ticks.length.x = NULL,
        axis.ticks.length.x.top = NULL,
        axis.ticks.length.x.bottom = NULL,
        axis.ticks.length.y = NULL,
        axis.ticks.length.y.left = NULL,
        axis.ticks.length.y.right = NULL,
        axis.title.x = ggplot2::element_text(margin = ggplot2::margin(t = base_size/4), vjust = 1),
        axis.title.x.top = ggplot2::element_text(margin = ggplot2::margin(b = base_size/4), vjust = 0),
        axis.title.y = ggplot2::element_text(angle = 90, margin = ggplot2::margin(r = base_size/4), vjust = 1),
        axis.title.y.right = ggplot2::element_text(angle = -90, margin = ggplot2::margin(l = base_size/4), vjust = 0),
        legend.background = ggplot2::element_rect(colour = NA),
        legend.spacing = ggplot2::unit(base_size, "pt"), legend.spacing.x = NULL,
        legend.spacing.y = NULL,
        legend.margin = ggplot2::margin(base_size/2, base_size/2, base_size/2, base_size/2),
        legend.key = ggplot2::element_rect(fill = ifelse(dark_mode, "black", "white"), colour = NA),
        legend.key.size = ggplot2::unit(1.2, "lines"),
        legend.key.height = NULL,
        legend.key.width = NULL,
        legend.text = ggplot2::element_text(size = ggplot2::rel(0.8)),
        legend.text.align = NULL,
        legend.title = ggplot2::element_text(hjust = 0),
        legend.title.align = NULL,
        legend.position = "right",
        legend.direction = NULL,
        legend.justification = "center",
        legend.box = NULL,
        legend.box.margin = ggplot2::margin(0, 0, 0, 0, "cm"),
        legend.box.background = ggplot2::element_blank(),
        legend.box.spacing = ggplot2::unit(base_size, "pt"),
        panel.background = ggplot2::element_rect(fill = ifelse(dark_mode, "black", "white"), colour = NA),
        panel.border = ggplot2::element_rect(fill = NA, color=ifelse(dark_mode, "white", "black")),
        panel.grid = ggplot2::element_line(colour = ifelse(dark_mode, "grey20", "grey95")),
        panel.grid.major.x = ggplot2::element_blank(),
        panel.grid.minor = ggplot2::element_line(size = ggplot2::rel(0.5)),
        panel.grid.minor.y = ggplot2::element_blank(),
        panel.grid.minor.x = ggplot2::element_blank(),
        panel.spacing = ggplot2::unit(base_size/2, "pt"),
        panel.spacing.x = NULL, panel.spacing.y = NULL,
        panel.ontop = FALSE,
        strip.background = ggplot2::element_rect(fill = "grey85", colour = "black"),
        strip.text = ggplot2::element_text(colour = "black", size = ggplot2::rel(0.8),
              margin = ggplot2::margin(0.4 * base_size, 0.4 * base_size, 0.4 * base_size, 0.4 * base_size)),
        strip.text.x = NULL,
        strip.text.y = ggplot2::element_text(angle = -90),
        strip.text.y.left = ggplot2::element_text(angle = 90),
        strip.placement = "inside",
        strip.placement.x = NULL,
        strip.placement.y = NULL,
        strip.switch.pad.grid = ggplot2::unit(base_size/4, "pt"),
        strip.switch.pad.wrap = ggplot2::unit(base_size/4, "pt"),
        plot.background = ggplot2::element_rect(colour = ifelse(dark_mode, "black", "white")),
        plot.title = ggplot2::element_text(size = ggplot2::rel(1.2), hjust = 0, vjust = 1, margin = ggplot2::margin(b = base_size/2)),
        plot.title.position = "panel",
        plot.subtitle = ggplot2::element_text(hjust = 0, vjust = 1, margin = ggplot2::margin(b = base_size/2)),
        plot.caption = ggplot2::element_text(size = ggplot2::rel(0.8), hjust = 1, vjust = 1, margin = ggplot2::margin(t = base_size/2)),
        plot.caption.position = "panel",
        plot.tag = ggplot2::element_text(size = ggplot2::rel(1.2), hjust = 0.5, vjust = 0.5),
        plot.tag.position = "topleft",
        plot.margin = ggplot2::margin(base_size/2, base_size/2, base_size/2, base_size/2),
        complete = TRUE)
}
