#' Basic theme for ggplots
#'
#' @param base_size Size that various elements use.
#' @param base_family Font family to use.
#' @param base_line_size Defaults to base_size / 22.
#' @param base_rect_size Defaults to base_size / 22.
#'
#' @export
#'
#'

lb_theme <- function(base_size=11, base_family = "", base_line_size=base_size/22, base_rect_size=base_size/22) {
  theme(line = element_line(color = "black", size = base_line_size, linetype = 1, lineend = "butt"),
        rect = element_rect(fill = "white", color = "black", size = base_rect_size, linetype = 1),
        text = element_text(color = "black", family = base_family, face = "plain", size = base_size, lineheight = 0.9,
                hjust = 0.5, vjust = 0.5, angle = 0, margin = margin()),
        axis.line = element_blank(),
        axis.line.x = NULL,
        axis.line.y = NULL,
        axis.text = element_text(margin = margin(t = 0.8 * base_size / 4), vjust = 1, color="black"),
        axis.text.x.top = element_text(margin = margin(b = 0.8 * base_size / 4), vjust = 0),
        axis.text.y = element_text(margin = margin(r = 0.8 * base_size / 4), hjust = 1, vjust=0.5),
        axis.text.y.right = element_text(margin = margin(l = 0.8 * base_size / 4), hjust = 0),
        axis.ticks = element_line(colour = "black"),
        axis.ticks.length = unit(base_size / 4, "pt"),
        axis.ticks.length.x = NULL,
        axis.ticks.length.x.top = NULL,
        axis.ticks.length.x.bottom = NULL,
        axis.ticks.length.y = NULL,
        axis.ticks.length.y.left = NULL,
        axis.ticks.length.y.right = NULL,
        axis.title.x = element_text(margin = margin(t = base_size/4), vjust = 1),
        axis.title.x.top = element_text(margin = margin(b = base_size/4), vjust = 0),
        axis.title.y = element_text(angle = 90, margin = margin(r = base_size/4), vjust = 1),
        axis.title.y.right = element_text(angle = -90, margin = margin(l = base_size/4), vjust = 0),
        legend.background = element_rect(colour = NA),
        legend.spacing = unit(base_size, "pt"), legend.spacing.x = NULL,
        legend.spacing.y = NULL,
        legend.margin = margin(base_size/2, base_size/2, base_size/2, base_size/2),
        legend.key = element_rect(fill = "white", colour = NA),
        legend.key.size = unit(1.2, "lines"),
        legend.key.height = NULL,
        legend.key.width = NULL,
        legend.text = element_text(size = rel(0.8)),
        legend.text.align = NULL,
        legend.title = element_text(hjust = 0),
        legend.title.align = NULL,
        legend.position = "right",
        legend.direction = NULL,
        legend.justification = "center",
        legend.box = NULL,
        legend.box.margin = margin(0, 0, 0, 0, "cm"),
        legend.box.background = element_blank(),
        legend.box.spacing = unit(base_size, "pt"),
        panel.background = element_rect(fill = "white", colour = NA),
        panel.border = element_rect(fill = NA, color="black"),
        panel.grid = element_line(colour = "grey95"),
        panel.grid.major.x = element_blank(),
        panel.grid.minor = element_line(size = rel(0.5)),
        panel.grid.minor.y = element_blank(),
        panel.spacing = unit(base_size/2, "pt"),
        panel.spacing.x = NULL, panel.spacing.y = NULL,
        panel.ontop = FALSE,
        strip.background = element_rect(fill = "grey85", colour = "black"),
        strip.text = element_text(colour = "black", size = rel(0.8),
              margin = margin(0.4 * base_size, 0.4 * base_size, 0.4 * base_size, 0.4 * base_size)),
        strip.text.x = NULL,
        strip.text.y = element_text(angle = -90),
        strip.text.y.left = element_text(angle = 90),
        strip.placement = "inside",
        strip.placement.x = NULL,
        strip.placement.y = NULL,
        strip.switch.pad.grid = unit(base_size/4, "pt"),
        strip.switch.pad.wrap = unit(base_size/4, "pt"),
        plot.background = element_rect(colour = "white"),
        plot.title = element_text(size = rel(1.2), hjust = 0, vjust = 1, margin = margin(b = base_size/2)),
        plot.title.position = "panel",
        plot.subtitle = element_text(hjust = 0, vjust = 1, margin = margin(b = base_size/2)),
        plot.caption = element_text(size = rel(0.8), hjust = 1, vjust = 1, margin = margin(t = base_size/2)),
        plot.caption.position = "panel",
        plot.tag = element_text(size = rel(1.2), hjust = 0.5, vjust = 0.5),
        plot.tag.position = "topleft",
        plot.margin = margin(base_size/2, base_size/2, base_size/2, base_size/2),
        complete = TRUE)
}
